spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoBro
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          characterEncoding: UTF-8
          useUnicode: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

app:
  upload:
    path: ./uploads
    allowed-types:
      - image/jpeg
      - image/png
      - image/webp
    thumbnail:
      width: 300
      height: 200 